description: Um blog sobre tudo que aprendo.
baseurl: ""
url: "https://portaoitenta.github.io" 
title: "porta oitenta | Blog"

pygments: true
permalink: /post/:title
exclude: ['Gemfile','Gemfile.lock','Rakefile','.git']
paginate: 4
